import = [ "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
    size = 16.0

    [font.bold]
        family = "FiraCode Nerd Font"
        style  = "Bold"

    [font.bold_italic]
        family = "FiraCode Nerd Font"
        style  = "Bold Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font"
        style  = "Italic"

    [font.normal]
        family = "FiraCode Nerd Font"
        style  = "Regular"

    [font.offset]
        x = 0
        y = 0

[window]
padding               = { x = 2, y = 2 }
decorations           = "None"
opacity               = 0.80
blur                  = true

[scrolling]
history               = 65535

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[mouse]
#hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]
